### ISSUE TITLE
修改信号分析与处理实验三

### ISSUE THREAD

**Issue by phychi** [HITSZ-OpenAuto/AUTO2005#3]
我fork后pr了，不知道看不看得见，看下能不能修改。

**Comment by xiln7** [comment]
Thanks for your notice and I have merged your PR [here](https://github.com/HITSZ-OpenAuto/AUTO2005/pull/2). If you have further code to contribute to this repo or even this project, PR is always welcome!🙌 If you want to contact us or join us, feel free to [send a mail to us](mailto:hi@huang-zifeng.comhoa.moe)
