### ISSUE TITLE
考完了可以上传实验四的参考内容吗？

### ISSUE THREAD

**Issue by phychi** [HITSZ-OpenAuto/AUTO2005#4]
考完了可以上传实验四的参考内容吗？我们这一级的实验四的内容与项目里的不一样，其实本来我想传的，但是发现自己删了。

**Comment by xiln7** [comment]
可以上传实验四的参考内容。如果你的意思是想问一下有没有别的同学想上传实验4吗？我倒是有的，可能放假之后再传。

**Comment by OliverWu515** [comment]
可以的。上传到labs文件夹里。
